name: lecture3_lasttask
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2      # The base engine
  firebase_auth: ^5.7.0      # The auth specific logic
  google_fonts: ^8.0.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/welcomecat.jpg
    - assets/typingcat.gif
    - assets/logincat.gif
    - assets/phonereg.gif
  fonts:
    - family: MyCaveat
      fonts:
        - asset: assets/fonts/Caveat-VariableFont_wght.ttf
    - family: MyDancingScript
      fonts:
        - asset: assets/fonts/DancingScript-VariableFont_wght.ttf


