// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOYhcvGIMfnkaBl390zfyFe7XPFZN2u8M',
    appId: '1:667049597393:web:1427127830d757a77468f0',
    messagingSenderId: '667049597393',
    projectId: 'androidclass-1',
    authDomain: 'androidclass-1.firebaseapp.com',
    storageBucket: 'androidclass-1.firebasestorage.app',
    measurementId: 'G-F624ZN9VPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6BREExXLGT8RSufQuS47nSuMUf1SUwQw',
    appId: '1:667049597393:android:2ea465bfe5aa67f87468f0',
    messagingSenderId: '667049597393',
    projectId: 'androidclass-1',
    storageBucket: 'androidclass-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvinglFjRnGHqUaq-klyJZEP2WZA9uFxc',
    appId: '1:667049597393:ios:b3053bad25fc77e27468f0',
    messagingSenderId: '667049597393',
    projectId: 'androidclass-1',
    storageBucket: 'androidclass-1.firebasestorage.app',
    androidClientId: '667049597393-prgongv7mu6k37p1o34bih8sjgs4lh7h.apps.googleusercontent.com',
    iosClientId: '667049597393-ibus2sacs8q90aq8ukiuds11rfq04idj.apps.googleusercontent.com',
    iosBundleId: 'com.example.lecture3Lasttask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvinglFjRnGHqUaq-klyJZEP2WZA9uFxc',
    appId: '1:667049597393:ios:b3053bad25fc77e27468f0',
    messagingSenderId: '667049597393',
    projectId: 'androidclass-1',
    storageBucket: 'androidclass-1.firebasestorage.app',
    androidClientId: '667049597393-prgongv7mu6k37p1o34bih8sjgs4lh7h.apps.googleusercontent.com',
    iosClientId: '667049597393-ibus2sacs8q90aq8ukiuds11rfq04idj.apps.googleusercontent.com',
    iosBundleId: 'com.example.lecture3Lasttask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOYhcvGIMfnkaBl390zfyFe7XPFZN2u8M',
    appId: '1:667049597393:web:5f842835f7d042e37468f0',
    messagingSenderId: '667049597393',
    projectId: 'androidclass-1',
    authDomain: 'androidclass-1.firebaseapp.com',
    storageBucket: 'androidclass-1.firebasestorage.app',
    measurementId: 'G-M958ZCCEZF',
  );

}